### ISSUE TITLE
UI Epic

### ISSUE THREAD

**Issue by roborourke** [humanmade/Workflows#7]
User stories:

- [ ] I should be able to see a list of all my workflows so that I can edit them.
- [ ] I should be able to click a button to create a new workflow.
- [ ] I should be able to toggle whether a workflow is active or not, from the list and from the workflow edit screen.
- [ ] When I click on a workflow I should see an interface to edit it.
- [ ] I should be able to set and edit the name of the workflow
- [ ] I should be able to choose an event to trigger the workflow from in a section labelled ‘When should this workflow happen?’
- [ ] After choosing an event I should be able to set any options specific to the event that customise when it triggers the workflow
- [ ] I should be able to write the message to send to recipients under a section labelled ‘What message should be sent?’
- [ ] I should be able to see a list of and use special placeholders in the message such as post content depending on the data provided by the event
- [ ] I should be able to add actions to attach to the message
- [ ] I should be able to add custom actions by specifying the link text and a URL
- [ ] I should see a section labelled ‘Who should be notified?’ where I can choose a combination of users, user roles, email addresses or any predefined dynamic options
- [ ] I should see a section called ‘Where should we notify them?’ where I can choose a combination of the registered destinations for the notification.
- [ ] When I look at my user profile I should see options to disable notifications from any registered destination in the ‘Where’ section of the workflow.
